alang=en,eng,it,ita
hwdec=auto
save-position-on-quit=yes
save-watch-history=yes
slang=en,eng,it,ita
sub-auto=fuzzy
write-filename-in-watch-later-config=yes

[T480s]
profile-cond=io.open("/etc/hostname"):read("l")=="T480s"
ytdl-raw-options=format-sort=codec:vp9

[Zoom recordings]
profile-cond=path:find('_Recording_')
hr-seek=yes

