font=monospace:size=12

[bell]
urgent=yes
notify=yes

[url]
launch=gio open ${url}
osc8-underline=always

# https://codeberg.org/dnkl/foot/wiki#piping-last-command-s-output
[key-bindings]
pipe-command-output=[sh -c "f=$(mktemp) && cat - > $f && emacsclient -r -a '' $f; rm $f"] Control+Shift+g
