# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Always restore open sites when qutebrowser is reopened.
# Type: Bool
c.auto_save.session = True

# Search engines which can be used via the address bar. Maps a search
# engine name (such as `DEFAULT`, or `ddg`) to a URL with a `{}`
# placeholder. The placeholder will be replaced by the search term, use
# `{{` and `}}` for literal `{`/`}` signs. The search engine named
# `DEFAULT` is used when `url.auto_search` is turned on and something
# else than a URL was entered to be opened. Other search engines can be
# used by prepending the search engine name to the search term, e.g.
# `:open google qutebrowser`.
# Type: Dict
c.url.searchengines = {
    'DEFAULT': 'https://duckduckgo.com/?q={}',
    'ar': 'https://www.archlinux.org/packages/?q={}',
    'au': 'https://aur.archlinux.org/packages/?O=0&K={}',
    'aw': 'https://wiki.archlinux.org/?search={}'
}

# Font family for sans-serif fonts.
# Type: FontFamily
c.fonts.web.family.sans_serif = 'Arial'

# Default font size (in pixels) for regular text.
# Type: Int
c.fonts.web.size.default = 14

# Bindings for normal mode
config.bind(',l', 'spawn --userscript qute-pass --password-only')
config.bind(',n',
            'config-cycle content.user_stylesheets ~/.solarized-dark.css ""')
config.bind(',p', 'spawn --userscript qute-pass')
config.bind(',u', 'spawn --userscript qute-pass --username-only')
config.bind('<Alt+Left>', 'back')
config.bind('<Alt+Right>', 'forward')
config.bind('M', 'hint links spawn mpv {hint-url}')
config.bind('m', 'spawn mpv {url}')

# Uncomment this to still load settings configured via autoconfig.yml
config.load_autoconfig()
